#server:
#  port: 1205
server:
#  port: 1200
  servlet:
    context-path: "/banking"

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/banking"
    username: "root"
    password: "root"
  sql:
    init:
      mode: ALWAYS
  jpa:
    hibernate:
      ddl-auto: update

upload:
  file:
    name: "profile-pictures/"

